### ISSUE TITLE
Pretrain availability 

### ISSUE THREAD

**Issue by VolodymyrAhafonov** [cxgincsu/SemanticGuidedHumanMatting#1]
Hello! Great work! I want to test pretrained weights shared by you on my test images. But I can't get access to pretrain on google disk. So could you please give access by link to pretrain on google drive?

**Comment by cxgincsu** [comment]
> Hello! Great work! I want to test pretrained weights shared by you on my test images. But I can't get access to pretrain on google disk. So could you please give access by link to pretrain on google drive?

Access is open to everyone.
