### ISSUE TITLE
load pretrained-weight error

### ISSUE THREAD

**Issue by xingha** [cxgincsu/SemanticGuidedHumanMatting#10]
Exception has occurred: RuntimeError
Error(s) in loading state_dict for HumanMatting:
	Missing key(s) in state_dict: "backbone.conv1.weight", "backbone.bn1.weight", "backbone.bn1.bias", "backbone.bn1.running_mean", "backbone.bn1.running_var", "backbone.layer1.0.conv1.weight", "backbone.layer1.0.bn1.weight", "backbone.layer1.0.bn1.bias", "backbone.layer1.0.bn1.running_mean", "backbone.layer1.0.bn1.running_var", "backbone.layer1.0.conv2.weight", "backbone.layer1.0.bn2.weight", "backbone.layer1.0.bn2.bias", "backbone.layer1.0.bn2.running_mean", "backbone.layer1.0.bn2.running_var", "backbone.layer1.0.conv3.weight", "backbone.layer1.0.bn3.weight", "backbone.layer1.0.bn3.bias", "backbone.layer1.0.bn3.running_mean", "backbone.layer1.0.bn3.running_var", "backbone.layer1.0.downsample.0.weight", "backbone.layer1.0.downsample.1.weight", "backbone.layer1.0.downsample.1.bias", "backbone.layer1.0.downsample.1.running_mean", "backbone.layer1.0.downsample.1.running_var", "backbone.layer1.1.conv1.weight", "backbone.layer1.1.bn1.weight",

**Comment by xingha** [comment]
![image](https://user-images.githubusercontent.com/15834669/213109723-fad0effd-bc21-4b12-b1fe-4e0185ef6136.png)

**Comment by cxgincsu** [comment]
You need to do : model = nn.DataParallel(model).cuda().eval()

**Comment by xingha** [comment]
谢谢，我是在cpu上跑的，加nn.DataParallel(model).to(‘cpu’).eval()可以跑了
