### ISSUE TITLE
Pretrained model of the segmentation part

### ISSUE THREAD

**Issue by ch1998** [cxgincsu/SemanticGuidedHumanMatting#11]
Great work. Can you provide the pretrained model of the segmentation part？ I want to test the effect of the segmentation.

**Comment by cxgincsu** [comment]
> Great work. Can you provide the pretrained model of the segmentation part？ I want to test the effect of the segmentation.

Our segmentation pretrain model is best_deeplabv3_resnet50_voc_os16.pth. See BMV2
You can extract our trained segmentation weights from SGHM-ResNet50.pth. The corresponding model parameters are: self.backbone、self.aspp、self.decoder in model/model.py.

**Comment by ch1998** [comment]
thank you for your reply
