### ISSUE TITLE
Np.int -> int

### ISSUE THREAD

**Issue by sklipnoty** [cxgincsu/SemanticGuidedHumanMatting#18]
Given

`AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidan
`

I had to replace 

`size = np.int(2 * half_size + 1)`

With

` size = int(2 * half_size + 1)`

Then everything works, great results!

**Comment by cxgincsu** [comment]
fixed
