### ISSUE TITLE
Retain the human texture

### ISSUE THREAD

**Issue by jerriebright** [cxgincsu/SemanticGuidedHumanMatting#4]
Hi, Great work!

I want to retain the texture of the human (instead of converting it to white). Can you assist me in how to do that (as shown in the videos in the paper's ablation study)?

If I am not wrong, I will have to retrain the matting module with texture-based training data. Correct me if I am wrong.

Let me know whenever possible. Thank you!

**Comment by cxgincsu** [comment]
> Hi, Great work!
> 
> I want to retain the texture of the human (instead of converting it to white). Can you assist me in how to do that (as shown in the videos in the paper's ablation study)?
> 
> If I am not wrong, I will have to retrain the matting module with texture-based training data. Correct me if I am wrong.
> 
> Let me know whenever possible. Thank you!

Thank you for your attention. Human texture ( foreground color ) is retrained at line 119 in test_video.py. (https://github.com/cxgincsu/SemanticGuidedHumanMatting/blob/master/test_video.py#:~:text=comp_np%20%3D%20alpha_np%20*%20frame_np%20%2B%20(1%20%2D%20alpha_np)%20*%20back_np)
