### ISSUE TITLE
Large image edge optimization is not very good

### ISSUE THREAD

**Issue by z411500976** [cxgincsu/SemanticGuidedHumanMatting#5]
Hi, Great work! 
it seems that the edge optimization of the large image is not very good, and there are some background colors. Is there any way to optimize it?
![QQ截图20221029134212](https://user-images.githubusercontent.com/24216715/198816041-24926425-79b0-4121-8346-09b3abc20cd5.png)

**Comment by cxgincsu** [comment]
> ere are some background colors. Is there
It is recommended to use a foreground estimation method when composing a new background. (1) https://github.com/PhotoRoom/fast-foreground-estimation (2) https://arxiv.org/pdf/2006.14970.pdf

**Comment by z411500976** [comment]
thank you for your reply
